# Site settings
title: LizardHQ research
description:
baseurl: "/lizardhq-website" # the subpath of your site, e.g. /blog/

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
